###

GET http://localhost:3000/

### 


GET http://localhost:3000/posts?owner=Amnon2


###

GET  http://localhost:3000/posts

###

POST  http://localhost:3000/posts
Content-Type: application/json

{
    "owner": "Amnon2",
    "title": "Post 2",
    "content": "Content 1"
}
### 

DELETE http://localhost:3000/posts/1